// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0UmPFanmqIhVHDdzCkL3hBRr_Ym-FBL0',
    appId: '1:409881013210:web:66774a92bee6f55c446ee3',
    messagingSenderId: '409881013210',
    projectId: 'restaurantfoodorderingap-a6f80',
    authDomain: 'restaurantfoodorderingap-a6f80.firebaseapp.com',
    storageBucket: 'restaurantfoodorderingap-a6f80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm18DTfGh86RsLdvTgNSUST8KPXirVT4g',
    appId: '1:409881013210:android:264dc82ba03e5713446ee3',
    messagingSenderId: '409881013210',
    projectId: 'restaurantfoodorderingap-a6f80',
    storageBucket: 'restaurantfoodorderingap-a6f80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASzGr0G0nP0CAPPqqUxAeEa4sNy8t9P2E',
    appId: '1:409881013210:ios:d48fbde81eaf3f8f446ee3',
    messagingSenderId: '409881013210',
    projectId: 'restaurantfoodorderingap-a6f80',
    storageBucket: 'restaurantfoodorderingap-a6f80.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASzGr0G0nP0CAPPqqUxAeEa4sNy8t9P2E',
    appId: '1:409881013210:ios:d48fbde81eaf3f8f446ee3',
    messagingSenderId: '409881013210',
    projectId: 'restaurantfoodorderingap-a6f80',
    storageBucket: 'restaurantfoodorderingap-a6f80.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0UmPFanmqIhVHDdzCkL3hBRr_Ym-FBL0',
    appId: '1:409881013210:web:b0851f55fbf8129d446ee3',
    messagingSenderId: '409881013210',
    projectId: 'restaurantfoodorderingap-a6f80',
    authDomain: 'restaurantfoodorderingap-a6f80.firebaseapp.com',
    storageBucket: 'restaurantfoodorderingap-a6f80.firebasestorage.app',
  );
}
